services:
  demirkiran-backend:
    # Kendi Docker Hub isminizle değiştirin
    image: kullaniciadi/demirkiran-backend:latest
    container_name: demirkiran-backend
    network_mode: host
    env_file: .env
    restart: unless-stopped
